get http://localhost:3000/todos/?status=TO%20DO

####
get http://localhost:3000/todos/?priority=LOW4

####
get http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

####
get http://localhost:3000/todos/?search_q=Buy

####
get http://localhost:3000/todos/?category=WORK&status=DONE

####
get http://localhost:3000/todos/?category=HOME45

####
get http://localhost:3000/todos/?category=LEARNING&priority=HIGH

####
get http://localhost:3000/todos/1/

#######
post http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 8,
  "todo": "Finalize event theme",
  "priority": "HIGH",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}

#######
put http://localhost:3000/todos/5/
Content-Type: application/json

{
      "dueDate": "2021-22-22"
    }
#########
delete http://localhost:3000/todos/8/

####
get http://localhost:3000/agenda/?date=2021-02-22