get http://localhost:3000/todos/
####
get http://localhost:3000/todos/?search_q=event
####
get http://localhost:3000/todos/10/
####

post http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 11,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
#######
delete http://localhost:3000/todos/11/
####